<script setup>
import { ref, watch } from 'vue'
import { partyApi } from '../services/api'
const props=defineProps({initial:String}); const emit=defineEmits(['found']); const q=ref(props.initial||'')
const rows=ref([]), loading=ref(false), error=ref(''), filter=ref('all')
const label = status => status === 'ACTIVE' ? 'Действует' : status === 'LIQUIDATING' ? 'Ликвидируется' : status === 'BANKRUPT' ? 'Банкротство' : status || 'Статус не указан'
const tone = status => status === 'ACTIVE' ? 'green' : status === 'LIQUIDATING' ? 'yellow' : 'red'
async function search(){ if(q.value.trim().length<2){error.value='Введите минимум два символа для поиска.';return}; loading.value=true;error.value='';try{rows.value=await partyApi.search(q.value.trim())}catch(e){rows.value=[];error.value=e.message}finally{loading.value=false} }
async function open(row){ if(!row.inn){error.value='У результата нет ИНН для открытия досье.';return}; loading.value=true;error.value='';try{emit('found',await partyApi.check(row.inn))}catch(e){error.value=e.message}finally{loading.value=false} }
watch(() => props.initial, value => { q.value=value||''; if(q.value) search() }, {immediate:true})
</script>
<template><div class="flex min-h-[calc(100vh-91px)]"><aside class="w-[410px] px-14 pt-10 text-[18px] text-[#9a9a9e]"><button class="flex w-full justify-between rounded-xl px-4 py-4" :class="filter==='all'?'bg-[#191919] text-white':''" @click="filter='all'">Все компании <span class="text-[#727277]">{{rows.length}}</span></button><div class="space-y-7 px-4 pt-6"><button v-for="item in [['ACTIVE','Действующие'],['LIQUIDATING','Ликвидируются'],['BANKRUPT','Банкротство']]" class="flex w-full text-left" :class="filter===item[0]&&'text-white'" @click="filter=item[0]">{{item[1]}}</button></div></aside><main class="flex-1 px-0 pt-10 pr-16"><form class="flex h-[76px] rounded-full border border-[#3b3b3d] bg-[#131313] p-2" @submit.prevent="search"><input v-model="q" class="flex-1 bg-transparent px-5 text-[20px] outline-none" placeholder="ИНН, название, руководитель или адрес"><button class="rounded-full bg-white px-7 text-[18px] text-black" :disabled="loading">{{loading?'Поиск…':'Найти'}}</button></form><div class="mt-5 flex justify-between text-[17px] text-[#8c8c91]"><span>{{rows.filter(r=>filter==='all'||r.status===filter).length}} компаний · запрос «{{q}}»</span><span>данные DaData</span></div><p v-if="error" class="mt-6 rounded-lg border border-red-900 bg-red-950/30 p-4 text-red-300">{{error}}</p><p v-else-if="!loading&&!rows.length" class="py-16 text-center text-[#8c8c91]">Введите запрос, чтобы найти компанию в DaData.</p><div class="mt-4"><button v-for="row in rows.filter(r=>filter==='all'||r.status===filter)" :key="row.inn" class="grid w-full grid-cols-[2.3fr_.7fr_.9fr_1fr] items-center border-b border-[#232323] py-8 text-left" @click="open(row)"><span><strong class="block text-[22px] font-medium">{{row.name}}</strong><small class="text-[17px] text-[#86868b]">{{row.director||'Руководитель не указан'}}</small></span><span class="text-[#b4b4b8]">{{row.inn||'—'}}</span><span class="text-[#b4b4b8]">{{row.city||row.address||'—'}}</span><span :class="tone(row.status)==='green'?'text-[#8ad6b0]':tone(row.status)==='yellow'?'text-[#e5c56f]':'text-[#e2989d]'">●&nbsp;{{label(row.status)}}</span></button></div></main></div></template>
